#!/bin/sh
set -e

cd ~/.vim_kim

echo '" DO NOT EDIT THIS FILE
" Add your customizations in ~/.vim_kim/my_configs.vim

set runtimepath+=~/.vim_kim

source ~/.vim_kim/vimrcs/basic.vim
source ~/.vim_kim/vimrcs/filetypes.vim
source ~/.vim_kim/vimrcs/plugins_config.vim
source ~/.vim_kim/vimrcs/extended.vim
try
  source ~/.vim_kim/my_configs.vim
catch
endtry' > ~/.vimrc

echo "Installing plugins..."
vim +PlugInstall +qall

echo "Installed vim_kim configuration successfully! Enjoy :-)"
